### ISSUE TITLE
صفحه جستجو

### ISSUE THREAD

**Issue by mhadiniknam** [mhadiniknam/AP-Twitter-Project#5]
صفحه جست وجو : امكان جست وجوي كاربر با استفاده از نام كاربري و نام و نام خانوادگي و سپسنمايشصفحه پروفايل
مربوطه و جست وجوي توييت با استفاده از شناسه توييت و متن توييت و نمايش صفحه توييت مربوطه فراهم باشد

**Comment by ParsaNaderiX** [comment]
Search Page implemented by adding 3 functions searchAccount(), searchTweet(), and searchPage(), and modifying main()!
